### ISSUE TITLE
Feature Request: Support FFI

### ISSUE THREAD

**Issue by drewbitt** [subframe7536/kysely-sqlite-tools#2]
Both [bun](https://bun.sh/docs/api/ffi) and [Deno](https://deno.land/manual@v1.35.3/runtime/ffi_api) have ffi. As seen on https://bun.sh/ SQLite benchmarks, the ffis put up impressive benchmarks for sqlite. Therefore it would be interesting to support their dialects. 

I could take a crack at it, although I can't get to it for a while, and so wanted to gauge interest here for implementing it.

**Comment by subframe7536** [comment]
So, according to my understanding, the way to implement it is just execute all SQL statements can be performed using FFI, just like kysely-sqlite-worker?

**Comment by drewbitt** [comment]
`kysely-sqlite-worker` code seems adaptable yes. Just import the FFI Database package and run the statements on it. And worker threads if they're useful here. older `bun` example without worker - https://github.com/dylanblokhuis/kysely-bun-sqlite/blob/master/src/driver.ts

**Comment by drewbitt** [comment]
Looks like Bun only has web workers for now. Worker threads will hit before they go 1.0 on Sept 7, so any day now.

**Comment by drewbitt** [comment]
Worker threads are available in bun 0.7.2

**Comment by subframe7536** [comment]
bun worker dialect have produced, but only using worker threads, currently no ffi

**Comment by subframe7536** [comment]
according to https://github.com/denodrivers/sqlite3#benchmark, bun:ffi is slower than bun:sqlite

**Comment by drewbitt** [comment]
Good note! I thought bun:sqlite was FFI originally as its similar in performance to Deno FFI but it is not.

**Comment by subframe7536** [comment]
a bun worker dialect is published
